# Site settings
name: Christophe Schwyzer
title: Stophe
email: hello@stophe.com
description: "Christophe Schwyzer's Interactive Portfolio"
baseurl: ""
url: "http://www.stophe.com"

# Build settings
markdown: kramdown
permalink: pretty

